### ISSUE TITLE
[ENHANCEMENT] Riffmaster Joystick

### ISSUE THREAD

**Issue by gamerbross** [TheNathannator/RB4InstrumentMapper#26]
Would be awesome to add compatibility with the Riffmaster joystick with analog movement and click

**Comment by TheNathannator** [comment]
The Riffmaster joystick should be supported already in ViGEmBus mode. Does it not work?

I'll need a packet log to look into this if it isn't already working:
- Enable the `Show packets` checkbox, then the `Log packets to file` checkbox.
- Hit Start, then move the joystick around for a bit.
- Hit Stop, and drag-and-drop the created packet log into here. It'll tell you where to find it in the console output.

The joystick isn't supported in vJoy mode since I don't want to change the mappings and require everyone using vJoy mode to re-do their bindings.

**Comment by gamerbross** [comment]
ok my bad, it actually does, clicking is recognized, **for me** isn't. This is my issue tho, i don't really know but i think my guitar drivers are scuffed. The whammy bar just toggles between -1 and 1, no decimals and the joystick movement is not recognized even in YARG, which supports riffmaster nativelly with every key possible, even solo keys. Do you know how could i fix this issue?

**Comment by gamerbross** [comment]
hey?

**Comment by TheNathannator** [comment]
Don't just say "hey" on a post lol, be direct with what you want.

If you're waiting for a response or a fix, refer to my first post. I'll need a packet log to look into this, I can't easily investigate without it.

**Comment by gamerbross** [comment]
i thought it wasnt necessary because it actually worked how it was suppoused to, but just not for me.
Moving the joystick shows nothing.
Clicking the joystick:
```
[2024-07-24 05:09:25.607] [33] -> 20 | 00-40-A1-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
[2024-07-24 05:09:26.199] [33] -> 20 | 00-00-A1-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
```
Moving the whammy:
```
[2024-07-24 05:09:46.291] [33] -> 20 | 00-00-A1-FF-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
[2024-07-24 05:09:48.160] [33] -> 20 | 00-00-A1-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
```

**Comment by gamerbross** [comment]
real question, how is waiting for who? are you waiting me to do something i really dont understand anymore

**Comment by gamerbross** [comment]
ok 👍

**Comment by gamerbross** [comment]
im gonna make a new issue with a better approach
